name: Build and Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: true
        default: 'v0.0.1'

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/drupal-advanced-queue-lambda:${{ github.event.inputs.tag }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/drupal-advanced-queue-lambda:${{ github.event.inputs.tag }}
